#
#   This services response with the semantic data association and the occupancy association
#
#   Response:
#       - ClassId: list of all class ids  
#       - classNameString: list of all class id name as string in the same order of ClassId
#       - occupancyClassId: list of all class ids for the occupancy association
#       - occupancyNameString: list of all occupancy name associations for each of the occupancyClassId (e.g., ground, ceiling, static, movable, dynamic)
#

---
#response

uint32[] ClassId
string[] classNameString

uint32[] occupancyClassId
string[] occupancyNameString
