#request

# trackedPts: list of TrackedVisibilityPt data to be added into map
#  if sent empty, no object data will be updated.
#  if sent with data, it will clear older data from list and add the newest data from message
TrackedVisibilityPt[] trackedPts

# if true, data will be clear.
bool clearObjects

---

#response

# state of whether the data was updated successfully
bool updated
