# THIS IS THE STRUCTURE REQUIRED FOR RTABMAP in SEMANTIC SEGMENTATION MODE

ground:
  earth;ground:
    id: 14
    color: [120, 120, 70]
  floor;flooring:
    id: 4
    color: [80, 50, 50]
  road;route:
    id: 7
    color: [140, 140, 140]
  grass:
    id: 10
    color: [4, 250, 7]
  land;ground;soil:
    id: 95
    color: [0, 194, 255]
  rug;carpet;carpeting:
    id: 29
    color: [255, 9, 92]
  sea: 
    id: 27
    color: [9, 7, 230]

ceiling:
  sky:
    id: 3
    color: [6, 230, 230]
  ceiling: 
    id: 6
    color: [120, 120, 80]

static:
  unknown:
    id: 0
    color: [0, 0, 0]
  wall: 
    id: 1
    color: [120, 120, 120] 
  building;edifice: 
    id: 2
    color: [180, 120, 120]  
  tree:
    id: 5
    color: [4, 200, 3]
  bed:
    id: 8
    color: [204, 5, 255]
  windowpane;window:
    id: 9
    color: [230, 230, 230]
  sidewalk;pavement: 
    id: 12
    color: [235, 255, 7]
  door;double;door:
    id: 15
    color: [8, 255, 51]
  mountain;mount:
    id: 17
    color: [143, 255, 140]
  plant;flora;plant;life:
    id: 18
    color: [204, 255, 4]
  curtain;drape;drapery;mantle;pall:
    id: 19
    color: [255, 51, 7]
  water:
    id: 22
    color: [61, 230, 250]
  shelf:
    id: 25
    color: [255, 7, 71]
  house:
    id: 26
    color: [255, 9, 224]
  mirror: 
    id: 28
    color: [220, 220, 220]
  field:
    id: 30
    color: [112, 9, 255]
  fence;fencing:
    id: 33
    color: [255, 184, 6]
  rock;stone: 
    id: 35
    color: [255, 41, 10]
  wardrobe;closet;press: 
    id: 36
    color: [7, 255, 255]
  bathtub;bathing;tub;bath;tub: 
    id: 38
    color: [102, 8, 255]
  railing;rail: 
    id: 39
    color: [255, 61, 6]
  cushion: 
    id: 40
    color: [255, 194, 7]
  base;pedestal;stand: 
    id: 41
    color: [255, 122, 8]
  column;pillar: 
    id: 43
    color: [255, 8, 41]
  signboard;sign: 
    id: 44
    color: [255, 5, 153]
  sand: 
    id: 47
    color: [160, 150, 20]
  sink: 
    id: 48
    color: [0, 163, 255]
  skyscraper: 
    id: 49
    color: [140, 140, 140]
  fireplace;hearth;open;fireplace: 
    id: 50
    color: [250, 10, 15]
  refrigerator;icebox: 
    id: 51
    color: [20, 255, 0]
  grandstand;covered;stand: 
    id: 52
    color: [31, 255, 0]
  path: 
    id: 53
    color: [155, 31, 0]
  stairs;steps: 
    id: 54
    color: [255, 31, 0]
  runway: 
    id: 55
    color: [153, 255, 0]
  case;display;case;showcase;vitrine: 
    id: 56
    color: [0, 0, 255]
  pool;table;billiard;table;snooker;table: 
    id: 57
    color: [255, 71, 0]
  screen;door;screen: 
    id: 59
    color: [0, 173, 255]
  stairway;staircase: 
    id: 60
    color: [31, 0, 255]
  river: 
    id: 61
    color: [11, 200, 200]
  bridge;span: 
    id: 62
    color: [255, 82, 0]
  bookcase: 
    id: 63
    color: [0, 255, 245]
  blind;screen: 
    id: 64
    color: [0, 61, 255]
  toilet;can;commode;crapper;pot;potty;stool;throne: 
    id: 66
    color: [0, 255, 133]
  flower: 
    id: 67
    color: [255, 0, 0]
  book: 
    id: 68
    color: [255, 163, 0]
  hill: 
    id: 69
    color: [255, 102, 0]
  bench: 
    id: 70
    color: [194, 255, 0]
  stove;kitchen;stove;range;kitchen;range;cooking;stove: 
    id: 72
    color: [51, 255, 0]
  palm;palm;tree: 
    id: 73
    color: [0, 82, 255]
  kitchen;island: 
    id: 74
    color: [0, 255, 41]
  bar: 
    id: 78
    color: [0, 255, 153]
  arcade;machine:
    id: 79
    color: [255, 92, 0]
  hovel;hut;hutch;shack;shanty:
    id: 80
    color: [255, 0, 255]
  light;light;source:
    id: 83
    color: [255, 173, 0]
  tower:
    id: 85
    color: [255, 184, 184]
  chandelier;pendant;pendent:
    id: 86
    color: [0, 31, 255]
  awning;sunshade;sunblind:
    id: 87
    color: [0, 255, 61]
  streetlight;street;lamp:
    id: 88
    color: [0, 71, 255]
  booth;cubicle;stall;kiosk:
    id: 89
    color: [255, 0, 204]
  dirt;track:
    id: 92
    color: [0, 10, 255]
  pole:
    id: 94
    color: [51, 0, 255]
  bannister;banister;balustrade;balusters;handrail:
    id: 96
    color: [0, 122, 255]
  escalator;moving;staircase;moving;stairway:
    id: 97
    color: [0, 255, 163]
  ottoman;pouf;pouffe;puff;hassock:
    id: 98
    color: [255, 153, 0]
  poster;posting;placard;notice;bill;card: 
    id: 101
    color: [143, 255, 0]
  stage: 
    id: 102
    color: [82, 0, 255]
  fountain: 
    id: 105
    color: [8, 184, 170]
  conveyer;belt;conveyor;belt;conveyer;conveyor;transporter: 
    id: 106
    color: [133, 0, 255]
  canopy: 
    id: 107
    color: [0, 255, 92]
  washer;automatic;washer;washing;machine: 
    id: 108
    color: [184, 0, 255]
  plaything;toy: 
    id: 109
    color: [255, 0, 31]
  swimming;pool;swimming;bath;natatorium: 
    id: 110
    color: [0, 184, 255]
  barrel;cask: 
    id: 112
    color: [255, 0, 112]
  basket;handbasket: 
    id: 113
    color: [92, 255, 0]
  waterfall;falls: 
    id: 114
    color: [0, 224, 255]
  tent;collapsible;shelter: 
    id: 115
    color: [112, 224, 255]
  cradle: 
    id: 118
    color: [153, 0, 255]
  oven: 
    id: 119
    color: [71, 255, 0]
  step;stair: 
    id: 122
    color: [255, 0, 143]
  tank;storage;tank: 
    id: 123
    color: [0, 255, 235]
  trade;name;brand;name;brand;marque: 
    id: 124
    color: [133, 255, 0]
  lake: 
    id: 129
    color: [10, 190, 212]
  dishwasher;dish;washer;dishwashing;machine: 
    id: 130
    color: [214, 255, 0]
  screen;silver;screen;projection;screen: 
    id: 131
    color: [0, 204, 255]
  sculpture: 
    id: 133
    color: [255, 255, 0]
  hood;exhaust;hood: 
    id: 134
    color: [0, 153, 255]
  sconce: 
    id: 135
    color: [0, 41, 255]
  vase: 
    id: 136
    color: [0, 255, 204]
  traffic;light;traffic;signal;stoplight: 
    id: 137
    color: [41, 0, 255]
  pier;wharf;wharfage;dock: 
    id: 141
    color: [71, 0, 255]
  crt;screen: 
    id: 142
    color: [122, 0, 255]
  bulletin;board;notice;board: 
    id: 145
    color: [184, 255, 0]
  shower: 
    id: 146
    color: [0, 133, 255]
  radiator: 
    id: 147
    color: [255, 214, 0]
  
movable:
  box: 
    id: 42
    color: [0, 255, 20]
  chest;of;drawers;chest;bureau;dresser: 
    id: 45
    color: [6, 51, 255]
  counter: 
    id: 46
    color: [235, 12, 255]
  countertop: 
    id: 71
    color: [0, 143, 255]
  buffet;counter;sideboard: 
    id: 100
    color: [255, 112, 0]
  van: 
    id: 103
    color: [163, 255, 0]
  ship: 
    id: 104
    color: [255, 235, 0]
  towel:
    id: 82
    color: [255, 0, 102]
  armchair: 
    id: 31
    color: [8, 255, 214]
  seat: 
    id: 32
    color: [7, 255, 224]
  cabinet: 
    id: 11
    color: [224, 5, 255]
  table: 
    id: 16
    color: [255, 6, 82]
  chair: 
    id: 20
    color: [204, 70, 3]
  coffee;table;cocktail;table: 
    id: 65
    color: [0, 255, 112]
  blanket;cover:  
    id: 132
    color: [20, 0, 255]
  bag:  
    id: 116
    color: [70, 184, 160]
  minibike;motorbike:  
    id: 117
    color: [163, 0, 255]
  plate:  
    id: 143
    color: [0, 255, 184]
  monitor;monitoring;device:  
    id: 144
    color: [0, 92, 255]
  glass;drinking;glass:  
    id: 148
    color: [25, 194, 194]
  clock:  
    id: 149
    color: [102, 255, 0]
  flag:  
    id: 150
    color: [92, 0, 255]
  tray:  
    id: 138
    color: [41, 255, 0]
  ashcan;trash;can;garbage;can;wastebin;ash;bin;ash-bin;ashbin;dustbin;trash;barrel;trash;bin:  
    id: 139
    color: [173, 0, 255]
  fan:  
    id: 140
    color: [0, 245, 255]
  microwave;microwave;oven:  
    id: 125
    color: [255, 0, 235]
  pot;flowerpot:  
    id: 126
    color: [245, 0, 255]
  ball:  
    id: 120
    color: [255, 0, 163]
  food;solid;food:  
    id: 121
    color: [255, 204, 0]
  bottle: 
    id: 99
    color: [0, 255, 10]
  television;television;receiver;television;set;tv;tv;set;idiot;box;boob;tube;telly;goggle;box: 
    id: 90
    color: [0, 255, 194]
  airplane;aeroplane;plane: 
    id: 91
    color: [0, 255, 82]
  swivel;chair: 
    id: 76
    color: [10, 0, 255]
  car;auto;automobile;machine;motorcar: 
    id: 21
    color: [0, 102, 200]
  stool:  
    id: 111
    color: [0, 214, 255]
  apparel;wearing;apparel;dress;clothes: 
    id: 93
    color: [0, 112, 255]
  computer;computing;machine;computing;device;data;processor;electronic;computer;information;processing;system: 
    id: 75
    color: [0, 255, 173]
  pillow: 
    id: 58
    color: [0, 235, 255]
  sofa;couch;lounge: 
    id: 24
    color: [11, 102, 255]
  boat: 
    id: 77
    color: [173, 255, 0]
  bicycle;bike;wheel;cycle:  
    id: 128
    color: [255, 245, 0]
  painting;picture: 
    id: 23
    color: [255, 6, 51]
  lamp: 
    id: 37
    color: [224, 255, 8]
  desk: 
    id: 34
    color: [10, 255, 71]
  bus;autobus;coach;charabanc;double-decker;jitney;motorbus;motorcoach;omnibus;passenger;vehicle: 
    id: 81
    color: [255, 0, 245]
  truck;motortruck: 
    id: 84
    color: [255, 0, 20]

dynamic:
  person;individual;someone;somebody;mortal;soul: 
    id: 13
    color: [150, 5, 61]
  animal;animate;being;beast;brute;creature;fauna:  
    id: 127
    color: [255, 0, 122]